sh ./heroku-login.sh "timothychidley@yahoo.com" && heroku container:login;
heroku create chidleyapp1;
heroku create chidleyapp2;
heroku create chidleyapp3;
heroku create chidleyapp4;
heroku create chidleyapp5;
heroku container:push web --app chidleyapp1;
heroku container:push web --app chidleyapp2;
heroku container:push web --app chidleyapp3;
heroku container:push web --app chidleyapp4;
heroku container:push web --app chidleyapp5;

sh ./heroku-login.sh "hamishperkins@yahoo.com" && heroku container:login;
heroku create hamishapp1;
heroku create hamishapp2;
heroku create hamishapp3;
heroku create hamishapp4;
heroku create hamishapp5;
heroku container:push web --app hamishapp1;
heroku container:push web --app hamishapp2;
heroku container:push web --app hamishapp3;
heroku container:push web --app hamishapp4;
heroku container:push web --app hamishapp5;

sh ./heroku-login.sh "nepeansebastian@yahoo.com" && heroku container:login;
heroku create nepeanapp1;
heroku create nepeanapp2;
heroku create nepeanapp3;
heroku create nepeanapp4;
heroku create nepeanapp5;
heroku container:push web --app nepeanapp1;
heroku container:push web --app nepeanapp2;
heroku container:push web --app nepeanapp3;
heroku container:push web --app nepeanapp4;
heroku container:push web --app nepeanapp5;
